### ISSUE TITLE
感谢作者提取的 tmux，非常好用，特来感谢

### ISSUE THREAD

**Issue by xnng** [hongwenjun/tmux_for_windows#1]

**Comment by hongwenjun** [comment]
把  .tmux.conf 放到 ~/ 目录下，支持鼠标操作

**Comment by xnng** [comment]
创建了，确实可以。我一开始只复制了 `/usr/bin` 文件夹里的内容，发现鼠标操作无效，后来发现还有个 `/usr/share` 文件夹，把这个也复制进去就好了。
