### ISSUE TITLE
windows termianl 出现open terminal failed: not a terminal 错误

### ISSUE THREAD

**Issue by zFitness** [hongwenjun/tmux_for_windows#2]
我在微软最新开发的 windows terminal 里面的git bash使用报错了
```bash
zfitness@DESKTOP-FC3LVMM MINGW64 /d
$ tmux new -s works
open terminal failed: not a terminal
```
但是直接在Git bash里面使用没有报错。

**Comment by hongwenjun** [comment]
我没用过 windows terminal  ，你试试看这个帖子
https://stackoverflow.com/questions/25207909/tmux-open-terminal-failed-not-a-terminal

**Comment by ghost** [comment]
似乎无法在命令行里运行git-bash，命令行里运行git-bash实际上会新打开一个MingW窗口，而命令行不会输出任何内容，在非MingW终端里运行tmux就会报这个错，可能只支持MingW。
实际上我是配置Windows上的ssh才发现Windows没有能直接用的tmux，导致ssh断开之后程序也没了

**Comment by holmofy** [comment]
我也碰到这个问题了

**Comment by Tastror** [comment]
试试 script -c tmux

**Comment by bethe410** [comment]
用惯了windows terminal再来找tmux for windows，很可惜用不了

**Comment by hongwenjun** [comment]
> 用惯了windows terminal再来找tmux for windows，很可惜用不了

![11](https://github.com/user-attachments/assets/ee384ee5-5916-4cae-9284-05b0652c01fb)

Windows 安装 git for windows ，会有个 mintty MINGW64环境，
只有在这个环境才可以使用 tmux 和 fish
