### ISSUE TITLE
tmux运行python程序后中文显示乱码

### ISSUE THREAD

**Issue by xldistance** [hongwenjun/tmux_for_windows#4]
还有按pageup不能往上翻页

**Comment by xldistance** [comment]
git bash里面试了几种中文字体，字符集里面试了utf-8，gbk都不行，中文乱码

**Comment by hongwenjun** [comment]
python 在 windows 是 winpty 程序

编辑  ~/.bashrc

alias python3='_win_python() { winpty python $@ ; }; _win_python'
alias python='_win_python() { winpty python $@ ; }; _win_python'


cat .tmux.conf
# マウス操作を有効にする
setw -g mouse
set-option -g history-limit 20000
set-option -g mouse on
bind -n WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -n WheelDownPane select-pane -t= \; send-keys -M
