### ISSUE TITLE
tmux跟fish有两个问题

### ISSUE THREAD

**Issue by ayuayue** [hongwenjun/tmux_for_windows#5]
1.` tmxu `
现在只能在 git-bash 中才能使用，使用 `WindowsTerminal` 启动的 git/bin/bash 无法使用。`cmder alacritty` 同样无法使用 
会提示  `open terminal failed: not a terminal`
2. `fish`
`fish_config` 没有反应

**Comment by hongwenjun** [comment]
我只测试在 git-bash 中使用， WindowsTerminal 没测试过，你使用旧版 tmux 试试
fish  也只是试用了基本功能
